spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:inditex
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect